
# Using empty (for now) pytest.ini file,
# this allows to force rootdir to the same directory than this file.
# Sub-allowing the top-level conftest.py file to be loaded and our custom pytest markers/options too.

# do not remove.

# See: https://docs.pytest.org/en/stable/reference/customize.html#finding-the-rootdir

[pytest]
# pytest options goes here

# enabled random order (globally) by default:
addopts = --random-order --random-order-bucket=global

testpaths =
    tests


# easily customize logging per your need:

# Enable live logging to the console
# log_cli = true

# Set the minimum log level to capture (DEBUG, INFO, WARNING, ERROR, CRITICAL)
log_cli_level = INFO

# Define the visual look of your logs
log_cli_format = %(asctime)s %(threadName)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)

# Define the date and time format
log_cli_date_format = %Y-%m-%d %H:%M:%S
