# -*- coding: utf-8 -*-
"""
This will generate a list of pseudo-random numbers that is identical to the
ones generated by the Arduino that produces the TTL outputs for aligning
external hardware to the RCP task cart. These numbers ranging 1 through 10
will match the number of pulses generated each second during camera recording
and output from FIO4 aka 'Extra Digital Out' as a chain of 5 ms HIGH, 5 ms LOW.
"""

 

 

class SimpleLCG:
    def __init__(self, seed=12345):
        self.state = seed & 0xFFFFFFFF

 

    def next_random(self):
        self.state = (1664525 * self.state + 1013904223) & 0xFFFFFFFF
        return self.state

 

    def pulse_count(self):
        return 1 + (self.next_random() % 10)

 

 

rec_dur = 3600; # duration of recording in seconds

 

rng = SimpleLCG(seed=12345)

 

# Expected pulse counts from Arduino
pulse_counts = [rng.pulse_count() for _ in range(rec_dur)]

 

 

# print(pulse_counts)
print(pulse_counts[-10:])
