n_back:
  settings:
  - Audio
  - Cameras
  - Button
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - TENS
  - leftCamTop
  - rightCamTop
naturalistic_speech:
  settings:
  - Audio
  - Cameras
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - TENS
  - leftCamTop
  - rightCamTop
motor_task_finger_taps:
  settings:
  - Audio
  - Cameras
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - TENS
  - leftCamTop
  - rightCamTop
diadochokinesis:
  settings:
  - Audio
  - Cameras
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - TENS
  - leftCamTop
  - rightCamTop
verbal_fluency:
  settings:
  - Audio
  - Cameras
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - TENS
  - leftCamTop
  - rightCamTop
vowel_space:
  settings:
  - Audio
  - Cameras
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - TENS
  - leftCamTop
  - rightCamTop
reach_grasp:
  settings:
  - Audio
  - Cameras
  - Photodiode
  - Grasp Button
  - Microphone 1
  - Microphone 2
  - Force Sensor X
  - Force Sensor Y
  - Force Sensor Z
  - Barcode
  - TENS
  - leftCamTop
  - rightCamTop
  - leftCamTripod
  - rightCamTripod
tone_taps_closed:
  settings:
  - Audio
  - Cameras
  - Button
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - TENS
  - leftCamTop
  - rightCamTop
sara:
  settings:
  - Audio
  - Cameras
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - TENS
  - leftCamTop
  - rightCamTop
verb_generation:
  settings:
  - Audio
  - Cameras
  - Photodiode
  - Microphone 1
  - Microphone 2
  - Barcode
  - TENS
  - leftCamTop
  - rightCamTop