naturalistic_speech:
  settings:
  - Photodetector
  - Subject Mic
  - Experimenter Mic
  - PC Audio
  - Camera Sync TTL
  - Return From DS7A
  - Trigger to DS7A
  - TTL to E-Phys
  - leftCamTop
  - rightCamTop
  - leftCamFace
  - rightCamFace
n_back:
  settings:
  - Photodetector
  - Subject Mic
  - Experimenter Mic
  - PC Audio
  - Camera Sync TTL
  - Return From DS7A
  - Trigger to DS7A
  - TTL to E-Phys
  - Digital Accessory
  - leftCamTop
  - rightCamTop
  - leftCamFace
  - rightCamFace
motor_task_finger_taps:
  settings:
  - Photodetector
  - Subject Mic
  - Experimenter Mic
  - PC Audio
  - Camera Sync TTL
  - Return From DS7A
  - Trigger to DS7A
  - TTL to E-Phys
  - leftCamTop
  - rightCamTop
  - leftCamFace
  - rightCamFace
diadochokinesis:
  settings:
  - Photodetector
  - Subject Mic
  - Experimenter Mic
  - PC Audio
  - Camera Sync TTL
  - Return From DS7A
  - Trigger to DS7A
  - TTL to E-Phys
  - leftCamTop
  - rightCamTop
  - leftCamFace
  - rightCamFace
verbal_fluency:
  settings:
  - Photodetector
  - Subject Mic
  - Experimenter Mic
  - PC Audio
  - Camera Sync TTL
  - Return From DS7A
  - Trigger to DS7A
  - TTL to E-Phys
  - leftCamTop
  - rightCamTop
  - leftCamFace
  - rightCamFace
vowel_space:
  settings:
  - Photodetector
  - Subject Mic
  - Experimenter Mic
  - PC Audio
  - Camera Sync TTL
  - Return From DS7A
  - Trigger to DS7A
  - TTL to E-Phys
  - leftCamTop
  - rightCamTop
  - leftCamFace
  - rightCamFace
reach_grasp:
  settings:
  - Photodetector
  - Subject Mic
  - Experimenter Mic
  - PC Audio
  - Grip Force Sensor
  - Force Sensor X
  - Force Sensor Y
  - Force Sensor Z
  - Camera Sync TTL
  - Grasp Start Pad
  - Return From DS7A
  - Trigger to DS7A
  - TTL to E-Phys
  - leftCamTop
  - rightCamTop
  - leftCamFace
  - rightCamFace
  - leftCamTripod
  - rightCamTripod
tone_taps_closed:
  settings:
  - Photodetector
  - Subject Mic
  - Experimenter Mic
  - PC Audio
  - Camera Sync TTL
  - Return From DS7A
  - Trigger to DS7A
  - TTL to E-Phys
  - Digital Accessory
  - leftCamTop
  - rightCamTop
  - leftCamFace
  - rightCamFace
sara:
  settings:
  - Photodetector
  - Subject Mic
  - Experimenter Mic
  - PC Audio
  - Camera Sync TTL
  - Return From DS7A
  - Trigger to DS7A
  - TTL to E-Phys
  - leftCamTop
  - rightCamTop
  - leftCamFace
  - rightCamFace
verb_generation:
  settings:
  - Photodetector
  - Subject Mic
  - Experimenter Mic
  - PC Audio
  - Camera Sync TTL
  - Return From DS7A
  - Trigger to DS7A
  - TTL to E-Phys
  - leftCamTop
  - rightCamTop
  - leftCamFace
  - rightCamFace
calibrate_top:
  settings:
  - Photodetector
  - Camera Sync TTL
  - Trigger to DS7A
  - TTL to E-Phys
  - leftCamTop
  - rightCamTop
  - leftCamFace
  - rightCamFace
calibrate_face:
  settings:
  - Photodetector
  - Camera Sync TTL
  - Trigger to DS7A
  - TTL to E-Phys
  - leftCamFace
  - rightCamFace
calibrate_tripod:
  settings:
  - Photodetector
  - Camera Sync TTL
  - Trigger to DS7A
  - TTL to E-Phys
  - leftCamTripod
  - rightCamTripod
  - leftCamFace
  - rightCamFace
